[package]
name = "circles"
version = "0.1.0"
authors = ["radix"]

[[bin]]
name = "circles"

[dependencies]
piston = "0.26.0"
piston2d-graphics = "0.19.0"
pistoncore-glutin_window = "0.31.0"
piston2d-opengl_graphics = "0.36.0"
time = "0.1"
ncollide = "0.10.0"
nalgebra = "0.9.*"
