[package]
name = "circles"
version = "0.1.0"
authors = ["radix"]

[[bin]]
name = "main"

[dependencies]
piston_window = "0.58.0"
ncollide = "0.10.0"
nalgebra = "0.9.*"
rand = "0.3.*"
find_folder = "0.3.0"
